## Lab 3: pandas

#### Introduction

We will examine a dataset containing characteristics of lego sets manufactured between 1961 and 2019 from the BRICKSET website. Variables in the dataset are described below.

| VARIABLE             |      DESCRIPTION             |
|:----------|:-------------|
| ID |  set id |
| Name |    name of set   |
| Themegroup | themegroup of set |
| Theme |  theme of set |
| Subtheme |    subtheme of set   |
| Year | year released |
| Pieces |  number of pieces |
| Minifig |    number of minifigs   |
| Package | type of packaging |
| Retail_Price |  recommended retail pri



Load pandas to read in the data and save it as dataframe named lego.

In [6]:
import pandas as pd

lego = pd.read_csv('/Users/shomokh/Desktop/SENIOR1ðŸ¥³ðŸ¥³ðŸ¥³/DS/lego.csv')
lego.sample(2) #random

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
12152,280-2,"Sloping Roof Bricks, Blue",Basic,System,Supplemental,1959.0,NaN,0,NaN,NaN
2828,30112-1,Emma's Flower Stand,Girls,Friends,NaN,2014.0,33.0,1,Polybag,4.99

#### Question 1:
Some sets have missing information for retail_price or pieces or both. This could be because the sets are free (giveaways), they arenâ€™t traditional lego sets (comic books, etc) or just because the information is missing. Filter the lego dataset based on the specifications below and save the result as lego. Hence, you will overwrite the original lego object. In addition, describe the implications of removing these sets.

Your new lego (data frame) should have:

â€¢ no missing pieces

â€¢ only contain sets with a nonzero number of pieces

â€¢ no missing retail_price

â€¢ only contain sets with a nonzero retail_price

â€¢ no missing year

- Print out the shape of the dataframe after cleaning the dataset.
-

In [35]:
# Write your answer here

# lego.shape

lego.pieces.max() 
lego.describe()  #only prints numerical columns

# lego.theme.unique()
# lego.theme.value_counts()


lego2=lego.dropna#drop missing rows with values not sure

               year        pieces      minifigs  retail_price
count  12213.000000  11125.000000  12214.000000   7849.000000
mean    2003.202817    201.429124      1.381775     28.547607
std       13.683488    382.014126      2.405519     41.036308
min     1955.000000      0.000000      0.000000      0.000000
25%     1997.000000     25.000000      0.000000      6.000000
50%     2007.000000     70.000000      1.000000     14.990000
75%     2014.000000    223.000000      2.000000     34.990000
max     2019.000000  10004.000000     36.000000    799.990000

In [49]:
#1
lego.shape

lego2=lego.dropna() #drop missing rows with values not sure

lego2.shape

(4360, 10)

In [68]:
#2

# Write your answer here
lego2.sample()

lego3=lego2.loc[lego2.pieces == 0, :] # no pices has value zero
lego3


lego3=lego2.loc[lego2.retail_price > 0, :]
lego3

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
1,10264-1,Corner Garage,Model making,Creator Expert,Modular Buildings,2019.0,2569.0,6,Box,199.99
2,10265-1,Ford Mustang,Model making,Creator Expert,Vehicles,2019.0,1471.0,0,Box,149.99
3,10766-1,Woody & RC,Licensed,Toy Story,Toy Story 4,2019.0,69.0,0,Box,9.99
4,10769-1,RV Vacation,Licensed,Toy Story,Toy Story 4,2019.0,178.0,0,Box,34.99
5,10770-1,Buzz & Woody's Carnival Mania!,Licensed,Toy Story,Toy Story 4,2019.0,230.0,0,Box,49.99
...,...,...,...,...,...,...,...,...,...,...
12082,805-2,3 Little Indians,Vintage themes,Samsonite,Model Maker,1964.0,89.0,0,Blister pack,0.98
12083,806-2,Cowboy & Pony,Vintage themes,Samsonite,Model Maker,1964.0,87.0,0,Blister pack,0.98
12091,520-4,2 X 2 Plate (Flat Roof Bricks with 4 Studs),Vintage themes,Samsonite,Supplemental,1961.0,40.0,0,Box,0.50
12092,7100-1,Samsonite Large Educational Set,Vintage themes,Samsonite,Educational,1963.0,3250.0,0,Wooden box,100.00
12106,215-3,2 X 8 Bricks,Vintage themes,Samsonite,Supplemental,1961.0,9.0,0,Box,0.50

#### Question 2:	
Arrange the dataset in descending order of retail_price and print the first three rows. Report in words the names of the three most expensive lego sets, their prices, and how many pieces each has.

In [73]:
lego2.sort_values(by='retail_price', ascending = False).head(3)# most expensive

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
1434,75192-1,Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2017.0,7541.0,8,Box,799.99
2065,75159-1,Death Star,Licensed,Star Wars,Ultimate Collector Series,2016.0,4016.0,27,Box,499.99
5944,10179-1,Ultimate Collector's Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2007.0,5197.0,5,Box,499.99

#### Question 3:

It appears that the most expensive sets generally have more pieces. Create a new variable (column) price_per_piece, representing the price in dollars per piece for each of the sets. Save the result as lego2. Hence, you will overwrite the current lego object.

In [85]:
# Write your answer here
lego2['price_per_piece'] = lego2.retail_price / lego2.pieces 

lego2.sort_values(by='price_per_piece', ascending = False)

/var/folders/0g/fswb2cc54z5_vs7nnnnzlsp00000gn/T/ipykernel_27171/1820300435.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lego2['price_per_piece'] = lego2.retail_price / lego2.pieces

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price,price_per_piece
5551,8878-1,Rechargeable Battery Box,Technical,Power Functions,Accessories,2009.0,1.0,0,Polybag,49.99,49.990
5553,8887-1,Transformer 10V DC,Technical,Power Functions,Accessories,2009.0,1.0,0,Polybag,29.99,29.990
5616,COMCON005-1,Collectable Display Set 2,Licensed,Star Wars,Miscellaneous,2009.0,2.0,3,Plastic box,49.99,24.995
8694,9755-1,Temperature Sensor,Technical,Mindstorms,1.0,1999.0,1.0,0,Polybag,24.00,24.000
7540,3805-1,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.5,2001.0,1.0,0,Other,20.00,20.000
...,...,...,...,...,...,...,...,...,...,...,...
4433,SAARBRUCKEN-1,"SaarbrÃ¼cken, Germany Exclusive Minifigure Pack",Miscellaneous,Promotional,LEGO brand store opening set,2012.0,15.0,3,Blister pack,0.00,0.000
4430,NASHVILLE-1,Nashville Exclusive Minifigure Pack,Miscellaneous,Promotional,LEGO brand store opening set,2012.0,15.0,3,Blister pack,0.00,0.000
4427,ELIZABETH-1,Elizabeth Exclusive Minifigure Pack,Miscellaneous,Promotional,LEGO brand store opening set,2012.0,15.0,0,Blister pack,0.00,0.000
4417,ALPHARETTA-1,Alpharetta Exclusive Minifigure Pack,Miscellaneous,Promotional,LEGO brand store opening set,2012.0,15.0,3,Blister pack,0.00,0.000
4030,40041-1,Moose,Miscellaneous,Promotional,Monthly Mini Model Build,2012.0,27.0,0,Polybag,0.00,0.000

#### Question 4:	

Arrange the lego2 dataset in descending order of price_per_piece and return only the columns: name, themegroup, theme, pieces, price_per_piece, and the first five rows. What do you notice about these sets?

In [87]:
# Write your answer here
# lego2.sort_values(by='price_per_piece', ascending = False).loc[ : , ['name', 'themegroup', 'theme', 'pieces', 'price_per_piece'] ]


lego3 = lego2.sort_values(by='price_per_piece', ascending = False)
lego3 = lego3.loc[ : , ['name', 'themegroup', 'theme', 'pieces', 'price_per_piece'] ]
lego3.head(5)

,name,themegroup,theme,pieces,price_per_piece
5551,Rechargeable Battery Box,Technical,Power Functions,1.0,49.990
5553,Transformer 10V DC,Technical,Power Functions,1.0,29.990
5616,Collectable Display Set 2,Licensed,Star Wars,2.0,24.995
8694,Temperature Sensor,Technical,Mindstorms,1.0,24.000
7540,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.0,20.000

#### Question 5:

What is the mean price_per_piece for the top 40 'Toy Story' sets in terms of price_per_piece?

In [97]:
# Write your answer here

lego3 = lego2.sort_values(by='price_per_piece', ascending = False)
lego3.loc[lego3.theme == 'Toy Story', :].head(40).price_per_piece.mean()
#rows where theme equal to toystory

0.16089862892544177

#### Question 6:

What are the unique themes in the lego dataset?

In [105]:
# Write your answer here
lego.theme.unique()

lego3.theme.value_counts()

theme
Star Wars                  503
Collectable Minifigures    431
City                       391
Town                       310
Racers                     183
                          ...
Monster Fighters             2
LEGOLAND                     1
Bricks and More              1
Books                        1
Explore                      1
Name: count, Length: 73, dtype: int64